baseURL = 'https://megabits.xyz/'
languageCode = 'zh-cn'
title = 'ğŸ¤ é‡‘é±¼çš„è®°å¿†ä»“åº“'

theme = "paper"
enableInlineShortcodes = true

[params]
  author = "Megabits"
  description = "ä½ å¥½ï¼Œè¿™äº›ä¸œè¥¿æ˜¯ä¸€æ¡é±¼çš„è®°å¿†ã€‚å‡å¦‚ä»–å¿˜äº†ä»€ä¹ˆçš„è¯ï¼Œè®°å¾—å»æé†’ä»–ã€‚"
  twitter = 'Megabits_mzq'                # twitter.com/YOUR_TWITTER_ID
#   github = 'megabitsenmzq'                  # github.com/YOUR_GITHUB_ID
  instagram = 'megabits_mzq'            # instagram.com/YOUR_INSTAGRAM_ID

[menu]
  [[menu.main]]
    identifier = "about"
    name = "è¿™ä¹ˆçƒ‚çš„ä¸œè¥¿è°å†™çš„"
    url = "/about/"
    weight = 10
    
[taxonomies]
    tag = "tags"